export const ID = Object.freeze({
  APP: 'app',
  PURCHASE_MENU: 'product-purchase-menu',
  MACHINE_MANAGE_MENU: 'vending-machine-manage-menu',
  PRODUCT_ADD_MENU: 'product-add-menu',
  PURCHASE_TAB: 'product-purchase-tab',
  MACHINE_MANAGE_TAB: 'vending-machine-manage-tab',
  PRODUCT_ADD_TAB: 'product-add-tab',
  NAME_INPUT: 'product-name-input',
  PRICE_INPUT: 'product-price-input',
  QUANTITY_INPUT: 'product-quantity-input',
  PRODUCT_ADD_BUTTON: 'product-add-button',
  MACHINE_CHARGE_INPUT: 'vending-machine-charge-input',
  MACHINE_CHARGE_BUTTON: 'vending-machine-charge-button',
  MACHINE_CHARGE_AMOUNT: 'vending-machine-charge-amount',
  MACHINE_COIN_500_QUANTITY: 'vending-machine-coin-500-quantity',
  MACHINE_COIN_100_QUANTITY: 'vending-machine-coin-100-quantity',
  MACHINE_COIN_50_QUANTITY: 'vending-machine-coin-50-quantity',
  MACHINE_COIN_10_QUANTITY: 'vending-machine-coin-10-quantity',
  CHARGE_INPUT: 'charge-input',
  CHARGE_BUTTON: 'charge-button',
  CHARGE_AMOUNT: 'charge-amount',
  COIN_RETURN_BUTTON: 'coin-return-button',
  COIN_500_QUANTITY: 'coin-500-quantity',
  COIN_100_QUANTITY: 'coin-100-quantity',
  COIN_50_QUANTITY: 'coin-50-quantity',
  COIN_10_QUANTITY: 'coin-10-quantity',
});

export const CLASS = Object.freeze({
  PRODUCT_MANAGE_NAME: 'product-manage-name',
  PRODUCT_MANAGE_PRICE: 'product-manage-price',
  PRODUCT_MANAGE_QUANTITY: 'product-manage-quantity',
  PRODUCT_PURCHASE_ITEM: 'product-purchase-item',
  PRODUCT_PURCHASE_BUTTON: 'purchase-button',
  PRODUCT_PURCHASE_NAME: 'product-purchase-name',
  PRODUCT_PURCHASE_PRICE: 'product-purchase-price',
  PRODUCT_PURCHASE_QUANTITY: 'product-purchase-quantity',
});
